Repository explosion/curated-transformers, pull requests merged in 2023-02, with the labels that each got.

#85 Batch the spans that are passed to the torch transformer model
  curated_transformers/models/with_strided_spans.py
  curated_transformers/pipe.py
  curated_transformers/tests/models/test_with_strided_spans.py
Labels: enhancement

#86 Fix MyPy errors and run in CI
  curated_transformers/models/hf_loader.py
  curated_transformers/models/transformer_model.py
  curated_transformers/models/with_non_ws_tokens.py
  setup.cfg
  tox.ini
Labels: bug

#94 Prefix encoders with `curated_encoder`
  curated_transformers/models/pytorch/curated_transformer.py
  curated_transformers/models/pytorch/hf_util.py
  curated_transformers/models/transformer_model.py
Labels: enhancement, feat/pytorch

#98 Fix import in quantize-transformer CLI
  curated_transformers/cli/quantize.py
  curated_transformers/tests/test_cli_app.py
Labels: bug

#84 Distillation: Make `TransformerDistiller` a no-op in regular pipelines
  curated_transformers/pipeline/distill.py
Labels: bug, feat/pipeline

#107 Move handling of adapters out of `build_transformer_model_v1`
  curated_transformers/models/architectures.py
  curated_transformers/tests/tokenization/test_xlmr_adapter.py
  curated_transformers/tokenization/hf_loader.py
  curated_transformers/tokenization/sentencepiece_encoder.py
Labels: enhancement, feat/tokenization

#106 `with_strided_spans`: only break on token boundaries
  curated_transformers/models/with_strided_spans.py
  curated_transformers/tests/models/test_with_strided_spans.py
Labels: enhancement, feat/pipeline

#109 Add support for lower casing and accent stripping to wordpiece encoders
  curated_transformers/tests/tokenization/test_wordpiece_encoder.py
  curated_transformers/tokenization/hf_loader.py
  curated_transformers/tokenization/wordpiece_encoder.py
Labels: enhancement, feat/tokenization

#110 Add character encoder
  .github/workflows/test.yml
  curated_transformers/_compat.py
  curated_transformers/tests/tokenization/test_char_encoder.py
  curated_transformers/tests/tokenization/toy-chars.txt
  curated_transformers/tokenization/__init__.py
  curated_transformers/tokenization/char_encoder.py
  curated_transformers/tokenization/hf_loader.py
  setup.cfg
Labels: enhancement, feat/tokenization

#112 Revert "`with_strided_spans`: only break on token boundaries (#106)"
  curated_transformers/models/with_strided_spans.py
  curated_transformers/tests/models/test_with_strided_spans.py
Labels: feat/pipeline

#115 Fix layer weighting config
  project/configs/layer-weighting.cfg
Labels: bug

#114 Add .gitignore
  .gitignore
Labels: enhancement

#111 Add `debug pieces` subcommand
  curated_transformers/cli/debug_pieces.py
  curated_transformers/tests/test_cli_app.py
  setup.cfg
Labels: enhancement, feat/cli
