Repository explosion/curated-transformers, pull requests merged in 2023-01, with the labels that each got.

#77 Speed up pooling by concatenating all transformer outputs
  curated_transformers/listener.py
  curated_transformers/models/pooling.py
  curated_transformers/models/types.py
  curated_transformers/tests/models/test_pooling.py
  requirements.txt
  setup.cfg
Labels: enhancement

#79 Increase GPU throughput during gradient accumulation
  curated_transformers/pipe.py
Labels: enhancement, feat/pipeline

#82 Add curated-transformers.TransformerLayersListener.v1
  curated_transformers/listener.py
  curated_transformers/tests/models/test_listeners.py
  requirements.txt
  setup.cfg
Labels: feat/pipeline
