Repository explosion/curated-transformers, pull requests merged in 2023-10, with the labels that each got.

#335 Remove unused model checkpoint context manager
  curated_transformers/repository/repository.py
  curated_transformers/tests/models/test_hf_hub.py
  curated_transformers/util/serde/checkpoint.py
  curated_transformers/util/serde/load.py
Labels: feat/misc, type/maintenance

#337 Set version to `1.4.0.dev0`
  setup.cfg
Labels: type/maintenance

#338 Set version to `1.3.0`
  setup.cfg
Labels: type/maintenance

#336 Add note to repo API on being experimental
  docs/source/repositories.rst
Labels: feat/doc, type/maintenance

#339 Update RTD links in Readme
  README.md
Labels: feat/doc, type/maintenance

#349 Add `AttentionScorer` abstraction
  curated_transformers/layers/__init__.py
  curated_transformers/layers/attention.py
  curated_transformers/models/albert/layer_group.py
  curated_transformers/models/bert/encoder.py
  curated_transformers/models/falcon/decoder.py
  curated_transformers/models/falcon/layer.py
  curated_transformers/models/gpt_neox/decoder.py
  curated_transformers/models/llama/decoder.py
  curated_transformers/models/mpt/decoder.py
  curated_transformers/models/roberta/encoder.py
  docs/source/api-compat.rst
  docs/source/building-blocks.rst
Labels: type/feature, feat/layers

#351 Register models using `catalogue`
  curated_transformers/__init__.py
  curated_transformers/models/albert/encoder.py
  curated_transformers/models/auto_model.py
  curated_transformers/models/bert/encoder.py
  curated_transformers/models/camembert/encoder.py
  curated_transformers/models/falcon/causal_lm.py
  curated_transformers/models/falcon/decoder.py
  curated_transformers/models/gpt_neox/causal_lm.py
  curated_transformers/models/gpt_neox/decoder.py
  curated_transformers/models/hf_hub/mixin.py
  curated_transformers/models/llama/causal_lm.py
  curated_transformers/models/llama/decoder.py
  curated_transformers/models/mpt/causal_lm.py
  curated_transformers/models/mpt/decoder.py
  curated_transformers/models/roberta/encoder.py
  curated_transformers/models/xlm_roberta/encoder.py
  docs/source/api.rst
  docs/source/registries.rst
  requirements.txt
  setup.cfg
Labels: type/feature, feat/model

#353 Bump the version to 2.0.0.dev0
  setup.cfg
Labels: type/maintenance

#352 AutoModel: let models check if the configuration is supported
  curated_transformers/models/albert/encoder.py
  curated_transformers/models/auto_model.py
  curated_transformers/models/bert/encoder.py
  curated_transformers/models/camembert/encoder.py
  curated_transformers/models/falcon/causal_lm.py
  curated_transformers/models/falcon/decoder.py
  curated_transformers/models/gpt_neox/causal_lm.py
  curated_transformers/models/gpt_neox/decoder.py
  curated_transformers/models/hf_hub/mixin.py
  curated_transformers/models/llama/causal_lm.py
  curated_transformers/models/llama/decoder.py
  curated_transformers/models/mpt/causal_lm.py
  curated_transformers/models/mpt/decoder.py
  curated_transformers/models/roberta/encoder.py
  curated_transformers/models/xlm_roberta/encoder.py
Labels: type/feature, feat/model
